services:
    benchmark:
        image: ubuntu-tcl-optimized
        volumes:
            - ./:/src/tinycc:ro
        working_dir: /build
        entrypoint: /src/tinycc/build_and_benchmark.sh

# vim: expandtab
