services:
    benchmark:
        image: ubuntu-tcl-optimized
        volumes:
            - ./:/src/jitc:ro
        working_dir: /build
        entrypoint: /src/jitc/build_and_benchmark.sh

# vim: expandtab
